services:
  warehouse-webapp:
    image: warehouse-webapp
    build:
      context: .
      dockerfile: WarehouseWebApp/Dockerfile
      
  mysql_warehouse_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data: